### ISSUE TITLE
Neat tool! A few minor issues

### ISSUE THREAD

**Issue by hmms117** [steineggerlab/folddisco#5]
Hi,

First of all, exciting work! I expect this may be yet another brilliant tool from the group 💪 

A small bug report - I am aware it was *just* released.

1. Rust/Cargo install: installed using the beta channel (correct?)

2. Foldseek query:
Works fine:

`folddisco query -i index/h_sapiens_folddisco -q "B57,B102,C195" -p query/4CHA.pdb -r -t 12 -v`

However, the README query example using *.txt file format fails:
```
folddisco query -i index/h_sapiens_folddisco -q query/serine_protease.txt -r -t 12

░█▀▀░█▀█░█░░░█▀▄░█▀▄░▀█▀░█▀▀░█▀▀░█▀█
░█▀▀░█░█░█░░░█░█░█░█░░█░░▀▀█░█░░░█░█
░▀░░░▀▀▀░▀▀▀░▀▀░░▀▀░░▀▀▀░▀▀▀░▀▀▀░▀▀▀

thread 'main' panicked at src/cli/workflows/query_pdb.rs:122:63:
[FAIL] Failed to open query file: query/serine_protease.txt: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

3. Using just positions without AA one letters fails for me. 

Works: zinc_finger.txt: 1G2F.pdb F207,F212,F225,F229
Fails: aminopeptidase.txt: 1LAP.pdb 250,255,273,332,334

Thanks!

**Comment by khb7840** [comment]
Thank you for the kind first issue!
Here's my responses.
1. For the beta channel, you mean the channels for cargo & rustc release, am I right? During the development, I've used the stable channel. But I think there would be no problem with the beta channel releases.
2. Current query file name is `query/serine_peptidase.txt`. Sorry for making confusions.
3. The first one letter before the position is the chain identifier. By default, it adds the first chain id in the PDB file. I cannot reproduce the error here. Can you share more details with commands?

**Comment by hmms117** [comment]
Thanks a lot for the clarifications. 
1. I could not install folddisco through cargo on stable - but this is likely my setup.
2. and 3. Ah, I assumed prefixes were AAs. Nevermind!

**Comment by khb7840** [comment]
Can you specify your cargo version? I'll try.

**Comment by hmms117** [comment]
cargo 1.83.0-beta.3 - but I think it's my server setup that is odd (Ubuntu 20.04). 

Closing - the core examples work 👍
